# Generated by Django 5.1.4 on 2025-01-02 20:57

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                (
                    "year_one_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "other_years_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("paystack_secret_key", models.CharField(max_length=200)),
                ("paystack_public_key", models.CharField(max_length=200)),
                ("google_app_password", models.CharField(max_length=200)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[600, 600],
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="logos/",
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"verbose_name_plural": "Departments",},
        ),
        migrations.CreateModel(
            name="PendingMomoPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_number", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "mobile",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be between 10 and 15 digits.",
                                regex="^\\d{10,15}$",
                            )
                        ],
                    ),
                ),
                ("level", models.IntegerField(default=100)),
                ("year_group", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.department",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Momo Payment",
                "verbose_name_plural": "Pending Momo Payments",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("ref_number", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "mobile",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be between 10 and 15 digits.",
                                regex="^\\d{10,15}$",
                            )
                        ],
                    ),
                ),
                ("year_group", models.IntegerField()),
                (
                    "unique_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.IntegerField(default=100)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="students.department",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="payments.payment",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
