# Generated by Django 5.1.4 on 2024-12-19 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "year_one_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "other_years_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("paystack_secret_key", models.CharField(max_length=200)),
                ("paystack_public_key", models.CharField(max_length=200)),
                ("google_app_password", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Departments",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("ref_number", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=15)),
                (
                    "unique_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="students.department",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="payments.payment",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
