# Generated by Django 5.1.4 on 2025-01-10 18:05

import django.core.files.storage
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[600, 600],
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="logos/",
            ),
        ),
    ]
