# Generated by Django 5.1.4 on 2024-12-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
        ("students", "0002_pendingregistration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PendingRegistration", new_name="PendingMomoPayment",
        ),
    ]
