# Generated by Django 5.1.4 on 2024-12-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_rename_pendingregistration_pendingmomopayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pendingmomopayment",
            options={
                "verbose_name": "Pending Momo Payment",
                "verbose_name_plural": "Pending Momo Payments",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="year_group",
            field=models.IntegerField(default=1),
        ),
    ]
