# Generated by Django 5.1.4 on 2025-01-14 06:01

import django.core.files.storage
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='has_tshirt_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='tshirt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount for T-shirt (only for first-year students)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 600], storage=django.core.files.storage.FileSystemStorage(), upload_to='logos/'),
        ),
    ]
