# Generated by Django 5.1.4 on 2025-01-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_department_has_tshirt_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='has_tshirt_program',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tshirt_amount',
        ),
    ]
