# Generated by Django 5.1.4 on 2024-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_pendingmomopayment_options_student_year_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingmomopayment",
            name="year_group",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student", name="year_group", field=models.IntegerField(),
        ),
    ]
