# Generated by Django 5.1.4 on 2024-12-24 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_pendingmomopayment_year_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingmomopayment",
            name="mobile",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be between 10 and 15 digits.",
                        regex="^\\d{10,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mobile",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be between 10 and 15 digits.",
                        regex="^\\d{10,15}$",
                    )
                ],
            ),
        ),
    ]
