# Generated by Django 5.1.4 on 2025-01-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_department_has_tshirt_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='offers_tshirt',
            field=models.BooleanField(default=False, verbose_name='Offers T-shirt'),
        ),
        migrations.AddField(
            model_name='department',
            name='tshirt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='T-shirt Amount'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_option',
            field=models.CharField(choices=[('full_payment', 'Full Payment (Dues + T-shirt)'), ('partial_payment', 'Partial Payment (Dues + Half T-shirt)'), ('dues_only', 'Dues Only')], default='dues_only', max_length=20),
        ),
    ]
