# Generated by Django 5.1.4 on 2025-01-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_department_offers_tshirt_department_tshirt_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='offers_tshirt',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tshirt_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_option',
        ),
    ]
