# Generated by Django 5.1.4 on 2024-12-26 20:13

import django.core.files.storage
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_pendingmomopayment_mobile_alter_student_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=85,
                scale=None,
                size=[600, 600],
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="logos/",
            ),
        ),
    ]
