# Generated by Django 5.1.4 on 2024-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_department_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingmomopayment",
            name="level",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="student", name="level", field=models.IntegerField(default=100),
        ),
    ]
