# Generated by Django 5.1.4 on 2024-12-29 00:59

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_department_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="full_name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[600, 600],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="logos/",
            ),
        ),
    ]
