# Generated by Django 5.1.4 on 2025-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_department_offers_tshirt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tshirt_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='tshirt_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='tshirt_option',
            field=models.CharField(choices=[('none', 'No T-shirt'), ('full', 'Full T-shirt Payment'), ('partial', 'Partial T-shirt Payment')], default='none', max_length=20),
        ),
    ]
