# Generated by Django 5.1.4 on 2024-12-30 21:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.files.storage
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
        ("students", "0010_department_full_name_alter_department_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[600, 600],
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="logos/",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["ref_number"], name="students_st_ref_num_f4939f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["full_name"], name="students_st_full_na_6ea9f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["email"], name="students_st_email_e271bc_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["unique_code"], name="students_st_unique__1b2161_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="students_st_search__87debe_gin"
            ),
        ),
    ]
