# Generated by Django 5.1.4 on 2025-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_department_tshirt_included_department_tshirt_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tshirt_option',
            field=models.CharField(choices=[('full', 'Full T-shirt Payment'), ('partial', 'Partial T-shirt Payment')], default='full', max_length=20),
        ),
    ]
