# Generated by Django 5.1.4 on 2024-12-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_add_search_vector_field"),
    ]

    operations = []
