# Generated by Django 5.1.4 on 2025-01-15 19:44

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_tshirt_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 600], storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='logos/'),
        ),
    ]
