# Generated by Django 5.1.4 on 2024-12-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_populate_search_vectors"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="student", name="students_st_ref_num_f4939f_idx",
        ),
        migrations.RemoveIndex(
            model_name="student", name="students_st_full_na_6ea9f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="student", name="students_st_email_e271bc_idx",
        ),
        migrations.RemoveIndex(
            model_name="student", name="students_st_unique__1b2161_idx",
        ),
        migrations.RemoveIndex(
            model_name="student", name="students_st_search__87debe_gin",
        ),
        migrations.RemoveField(model_name="student", name="search_vector",),
    ]
