# Generated by Django 5.1.4 on 2025-01-02 17:22

import cloudinary_storage.storage
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_remove_student_students_st_ref_num_f4939f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="department",
            name="service_charge",
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="department",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[600, 600],
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="logos/",
            ),
        ),
    ]
