# Generated by Django 5.1.4 on 2025-01-16 14:32

import django.core.files.storage
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_department_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[600, 600], storage=django.core.files.storage.FileSystemStorage(), upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tshirt_option',
            field=models.CharField(choices=[('full', 'Full T-shirt Payment'), ('partial', 'Partial T-shirt Payment'), ('none', 'No T-shirt')], default='none', max_length=20),
        ),
    ]
