# Generated by Django 5.1.4 on 2025-01-16 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_alter_department_image_alter_student_tshirt_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
