# Generated by Django on YYYY-MM-DD HH:MM
from django.db import migrations, models
import uuid


def populate_uuids(apps, schema_editor):
    Student = apps.get_model("students", "Student")  # Get the Student model
    for student in Student.objects.all():
        student.uuid = uuid.uuid4()  # Generate a unique UUID for each student
        student.save()  # Save the updated student


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_student_uuid_alter_student_id"),  # Depends on the previous migration
    ]

    operations = [
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
    ]
