# Generated by Django on YYYY-MM-DD HH:MM
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_auto_20250116_1944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
