# Generated by Django 5.1.4 on 2025-01-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20250116_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
