# Generated by Django 5.1.4 on 2025-01-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cash_service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='department',
            name='momo_service_charge',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='department',
            name='round_cash_payments',
            field=models.BooleanField(default=True),
        ),
    ]
