# Generated by Django 5.1.4 on 2025-01-18 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_department_cash_service_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='cash_service_charge',
        ),
        migrations.RemoveField(
            model_name='department',
            name='momo_service_charge',
        ),
        migrations.RemoveField(
            model_name='department',
            name='round_cash_payments',
        ),
    ]
