# Generated by Django 5.1.4 on 2025-01-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_department_cash_service_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='google_app_password',
        ),
        migrations.RemoveField(
            model_name='department',
            name='paystack_public_key',
        ),
        migrations.RemoveField(
            model_name='department',
            name='paystack_secret_key',
        ),
    ]
