# Generated by Django 5.1.4 on 2025-01-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
    ]
